/**
 * A per-workspace mutation counter, so an unchanged app shell costs no database.
 *
 * ── The problem this solves ───────────────────────────────────────────────
 * `/api/snapshot` is the whole shell in one request, polled every 8 seconds by
 * every signed-in tab. At 1,000 concurrent users that is ~125 req/s, each one
 * an auth resolution plus eight parallel queries — roughly 1,100 Postgres
 * queries per second generated by people who are doing nothing but having the
 * tab open. It is the single largest load the platform carries, and almost all
 * of it re-reads data that did not change.
 *
 * ── Why a TTL cache does NOT solve it ─────────────────────────────────────
 * The obvious fix — cache the response per (org, user) for ~5s — is close to
 * worthless here, and it is worth writing down why so nobody re-proposes it.
 * The poll interval is 8s and the TTL would be 5s, so a given user's next poll
 * almost always lands AFTER their own entry expired. The hit rate for the
 * traffic that actually exists is near zero. It caches nothing; it just adds a
 * round trip.
 *
 * What is actually true about this workload is that the data is nearly always
 * unchanged. So the question to ask per poll is not "do I have a recent copy"
 * but "has anything happened since the copy the CLIENT already has" — which is
 * exactly the question an ETag answers, provided computing the validator is
 * cheap. Deriving it from the payload would defeat the point (you would have
 * run every query to find out you did not need to). Hence a counter: one
 * integer per workspace, bumped on write, read on poll.
 *
 * A poll whose `If-None-Match` still matches returns 304 having executed ZERO
 * database queries. Idle users — the overwhelming majority at any moment — cost
 * one cache read each.
 *
 * ── Why the bump lives in the Prisma extension ────────────────────────────
 * The snapshot reads five models, written from far more than five places. If
 * the bump were called at each write site, the sixth one added later would
 * silently serve stale shells until someone noticed — and "the sidebar is a few
 * minutes behind" is a bug that gets lived with rather than reported. Putting
 * it at the same chokepoint the tenant guard and the run-data redaction already
 * use means a new write site is covered the day it is written. Same reasoning,
 * same place. See src/lib/prisma.ts.
 *
 * ── Failure mode ──────────────────────────────────────────────────────────
 * Deliberately fail-OPEN, in the direction of extra work rather than stale
 * data. With no cache backend configured, or with one that is down,
 * `readSnapshotVersion` returns null, no validator is emitted, and every poll
 * runs the queries exactly as it did before this file existed. The shell gets
 * slower, never wrong.
 */
import { cacheGetNumber, cacheIncrBy, cacheConfigured } from '@/lib/cache'
import { apiLogger } from '@/lib/logger'

/**
 * Models whose rows appear in — or change the value of — a snapshot response.
 *
 * `Organization` is here for the workspace name/plan/logo the sidebar renders;
 * `LlmCall` because the usage bar's denominator and numerator move with token
 * spend, and a credits bar that updates only when an agent row happens to
 * change would be wrong in the direction users notice.
 */
export const SNAPSHOT_MODELS = new Set([
  'AgentTask',
  'AgentExecution',
  'Notification',
  'Organization',
  'WorkspaceFolder',
  'LlmCall',
])

/**
 * A month is far longer than any counter needs to live, and that is the point:
 * the value only has to be MONOTONIC for as long as a client might hold an ETag
 * derived from it. If the key expired between two polls the counter would
 * restart at 1, and a client holding a higher number would match a version that
 * no longer means what it did. Expiring on a horizon no browser tab survives
 * makes that unreachable in practice, and the reset is harmless anyway: it can
 * only cause an extra recompute, never a stale serve, because a mismatch always
 * falls through to the queries.
 */
const VERSION_TTL_MS = 31 * 24 * 60 * 60 * 1000

function versionKey(organizationId: string): string {
  return `snapshot:ver:${organizationId}`
}

/** Current mutation counter for a workspace, or null when unavailable. */
export async function readSnapshotVersion(organizationId: string): Promise<number | null> {
  if (!cacheConfigured()) return null
  try {
    // A workspace that has never been written to has no key yet. Treat that as
    // version 0 rather than "unknown": it is a perfectly good validator, and
    // returning null there would permanently disable revalidation for quiet
    // workspaces — precisely the ones with the most to gain.
    return (await cacheGetNumber(versionKey(organizationId))) ?? 0
  } catch {
    return null
  }
}

/**
 * Advance a workspace's counter. Best-effort and never awaited by a write path:
 * a snapshot that recomputes one cycle late is invisible, whereas a user-facing
 * mutation that fails because a cache backend hiccuped is not.
 */
export function bumpSnapshotVersion(organizationId: string): void {
  if (!cacheConfigured() || !organizationId) return
  void cacheIncrBy(versionKey(organizationId), 1, VERSION_TTL_MS).catch((error) => {
    // Logged, not swallowed silently: sustained failures here mean every shell
    // poll is running the full query set, which is a capacity problem that
    // otherwise presents only as unexplained database load.
    apiLogger.warn('snapshot version bump failed', { organizationId, error: String(error) })
  })
}

/** Prisma operations that can change what a snapshot would return. */
const WRITE_OPERATIONS = new Set([
  'create', 'createMany', 'createManyAndReturn',
  'update', 'updateMany', 'updateManyAndReturn',
  'upsert', 'delete', 'deleteMany',
])

export function isSnapshotMutation(model: string | undefined, operation: string): boolean {
  return Boolean(model) && SNAPSHOT_MODELS.has(model as string) && WRITE_OPERATIONS.has(operation)
}

/**
 * The workspace a write belongs to, for counter purposes.
 *
 * `Organization` is the one model here that does not CARRY an organizationId —
 * it IS the organization — so its own id is the key. Everything else routes on
 * the scope the tenant guard already required, falling back to the ambient
 * organization for the parent-scoped models that have no column of their own.
 */
export function organizationIdForSnapshotBump(
  model: string | undefined,
  args: unknown,
  ambient: string | undefined,
): string | undefined {
  const where = (args as { where?: Record<string, unknown> } | undefined)?.where
  const data = (args as { data?: Record<string, unknown> } | undefined)?.data
  if (model === 'Organization') {
    const id = where?.id ?? (data as { id?: unknown } | undefined)?.id
    return typeof id === 'string' ? id : ambient
  }
  const scoped = where?.organizationId ?? (Array.isArray(data) ? undefined : (data as { organizationId?: unknown } | undefined)?.organizationId)
  return typeof scoped === 'string' ? scoped : ambient
}
