import { ARTIFACT_DESIGN_GUIDANCE } from './design-system'
import { ARTIFACT_MODULES } from './runtime'

/** What a TSX artifact may import, as the validator enforces it. */
export const ARTIFACT_IMPORT_LIST = Object.keys(ARTIFACT_MODULES).join(', ')

export const ARTIFACT_CAPABILITIES = ARTIFACT_DESIGN_GUIDANCE + '\n\n' + `ARTIFACT APPLICATION RUNTIME
HTML, CSS, JavaScript, TypeScript and React/TSX execute in the isolated artifact runtime. Return a complete working application, not mock buttons. Preserve HTML/Python when editing an existing page.
Imports available to React/TSX (vendored, nothing else resolves): ${ARTIFACT_IMPORT_LIST}, plus @backstory/artifact and the platform's @/components/ui/* primitives. Any other import fails validation, so use these or plain code. In HTML, load the same libraries by their usual CDN URLs (they swap to local copies). External images and fonts do not load: use data: URIs or inline SVG for logos and system fonts.
React may import { useArtifactState, runPython, cancelPython } from '@backstory/artifact'. HTML uses window.BackstoryArtifact. For durable editable records use const [records,setRecords,storage] = useArtifactState('records-v1', initialRecords). This private per-user state survives reloads and source revisions. Wait for storage.ready before enabling writes, show storage.saving/error, and never claim a failed save succeeded. On failure offer storage.retry(); storage.reload() explicitly discards the draft and reloads saved state. Export the draft before resolving conflicting changes. Use window.BackstoryArtifact.setDirty(true) for unsaved custom editor drafts and setDirty(false) after saving/discarding them; typing alone never marks the page dirty. Keep transient navigation/search in ordinary React useState. Writes to the same key within half a second are coalesced into one save, so binding a field to state is fine; still prefer saving on blur or submit for large records. Where there is no writable state (a public link, a view-only reader, a historical version) storage.ready becomes true with storage.readOnly set and set() keeps the value in memory only: show that the page is read-only rather than an error. Use stable, schema-versioned keys (letters, digits, underscore, hyphen, max 64); max 32 keys, 256 KB each. No secrets. Changing a key is an explicit data migration, not a cosmetic edit. Anonymous shares and historical versions have no writable state bridge. HTML loadState(key) returns {value,revision}; saveState(key,value,revision) uses optimistic concurrency. A conflict means reload/reconcile, never silently overwrite.
Shared state: const [sheet,setSheet,shared] = useSharedArtifactState('signups-v1', initial) (from '@backstory/artifact'; HTML: window.BackstoryArtifact.loadSharedState(key) / saveSharedState(key,value,revision)) is ONE value for everyone who opens the artifact — a sign-up sheet, a vote, a shared checklist, a team's notes — where useArtifactState is private to each person. Same keys, limits (max 32 keys, 256 KB each) and storage flags; anyone who can read the artifact reads it, anyone who can edit it writes it, and readers get shared.readOnly. Writes use the same revision check, so a conflict (someone else saved first) surfaces through shared.error with retry/reload — reload then re-apply is the usual answer. Other viewers do not see a change until they reload or the page re-reads (shared.reload()); offer an explicit refresh action rather than polling on a timer. Never put one person's private draft in shared state.
Runtime errors: when get_artifact returns renderErrors, those are the page's OWN runtime errors (uncaught exceptions, rejected promises, console.error) as the viewer captured them on the current version. A change request on a version with renderErrors must fix those first — find the failing code, correct it, and only then make the requested change; say what was broken in the reply. view_artifact_screenshot shows what the current version looks like.
Interactive artifacts MUST define window.__artifactTests = [{action:'fill',selector:'#name',value:'QA example'},{action:'click',selector:'#save'},{action:'expectText',selector:'#result',value:'QA example'}] in executable JavaScript/TSX, adapted to their REAL primary workflow. At most 20 steps; supported actions: fill, click, select, expectText, expectValue. Include both an action and meaningful observable assertion; stable selectors must actually exist. The isolated browser runs these steps with synthetic private state and no integration credentials before publishing. Test calculations, filters, edits and save results relevant to the request. Never write persistent state automatically on startup. A failed test keeps the previous version current. Do not bypass tests or claim they prove untested business rules.
Real Python is available: await runPython('sum(input["values"])', {values:[1,2,3]}, {timeoutMs:30000}) returns JSON-compatible output. Initialization is lazy and automatic in an isolated Pyodide Web Worker; stdlib/numpy/pandas are available. A computation must end in an expression for its return value. All Python, including inline HTML Python blocks, runs in a worker and has no DOM; exchange input/output with React/JS. Use JavaScript event listeners and rendering, never Python imports of document/window or create_proxy DOM handlers. Show loading, success and actionable errors. cancelPython() terminates current/queued calculations; timeouts terminate the worker. Do not merely check window.pyodide and declare Python unavailable. Never relabel a JS result as Python. Sequential inline blocks preserve their Python namespace and print output until cancellation or timeout resets the worker.
No arbitrary network, cookies, localStorage or sessionStorage. Do not weaken the sandbox. Backend integrations require an explicit platform capability. Make layouts responsive down to 320px: use border-box sizing, flexible wrapping and bounded inputs/buttons; confine wide tables to their own scrolling region. Keep all controls keyboard accessible; implement real validation, empty states, sorting, exports and derived calculations. Output length should follow required functionality, not a line-count target.`
